### ISSUE TITLE
Cant Run or Build Project After Flutter 2.2 Upgrade

### ISSUE THREAD

**Issue by Yoda-Man** [adrianflutur/webviewx#10]
C:\Flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter\InputAwareWebView.java:31: 
error: cannot find symbol
  private ThreadedInputConnectionProxyAdapterView proxyAdapterView;
          ^
  symbol:   class ThreadedInputConnectionProxyAdapterView
  location: class InputAwareWebView
C:\Flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-2.0.6\android\src\main\java\io\flutter\plugins\webviewflutter\InputAwareWebView.java:112: error: cannot find symbol
        new ThreadedInputConnectionProxyAdapterView(
            ^
  symbol:   class ThreadedInputConnectionProxyAdapterView
  location: class InputAwareWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors                                                                

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webview_flutter:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.        

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.   

* Get more help at https://help.gradle.org

BUILD FAILED in 53s

**Comment by adrianflutur** [comment]
Hi, you are experiencing this bug [flutter/#82803](https://github.com/flutter/flutter/issues/82803).
I have updated the version for webview_flutter. Please use this package from github until I publish a new version to pub.dev.
Thanks!
