### ISSUE TITLE
webviewx black screen in mobile view

### ISSUE THREAD

**Issue by CodingWithTashi** [adrianflutur/webviewx#11]
I am trying load local asset html from assets folder in flutter and while doing so it is working fine in web, thanks webviewx team but while viewing in mobile I am seeing black spot on top and html page is not rendering at all due to import issue
`
import 'package:flutter/material.dart';
import 'package:webviewx/webviewx.dart';

class FormDetailPage extends StatefulWidget {
  @override
  _FormDetailPageState createState() => _FormDetailPageState();
}

class _FormDetailPageState extends State<FormDetailPage> {
  WebViewXController webviewController;
  String title = 'Form Page';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: WebViewX(
        javascriptMode: JavascriptMode.unrestricted,
        initialContent:
            '<h2> Loading </h2><div style="height: 200px"></div><h2> Loading </h2>',
        initialSourceType: SourceType.HTML,
        onWebViewCreated: (controller) {
          webviewController = controller;
          //_loadHtmlFromAssets();
        },
      ),
    );
  }

}`

![issue 1](https://user-images.githubusercontent.com/25583737/119635199-129ebd00-be31-11eb-83ff-f550995d3b13.PNG)

**Comment by adrianflutur** [comment]
Hi, are you sure this is a problem coming from webviewx? I didn't encounter this behaviour so far.
Recently I have updated dependencies, including webview_flutter's version. Maybe give it a try again now to see if that was the issue.

If that does not fix the problem, please post the full code (including the html page you're using) for further investigation. 
Thanks

**Comment by CodingWithTashi** [comment]
Yes I have check again and still I am getting back spot but only in case of mobile device and I am using emulator to test.
I am using latest versin as well. webviewx: ^0.0.4. For now I am using two plugin for worekaround. But if you fix this issue it would be a great help.

Here is index.html from assets ([templete ](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_make_a_website)from w3school)

**Comment by adrianflutur** [comment]
Sorry, I should've been more explicit. By "give it a try now" I actually meant you should try to use the webviewx package from the main branch here, on github, instead of using it from pub.dev.

This is how it should be done:
```yaml
dependencies:
  webviewx:
    git: https://github.com/adrianflutur/webviewx.git
```

I didn't publish a new version yet because there are a few things that need to be addressed before I can increment the version to 0.0.5 and upload to pub.dev.

**Comment by CodingWithTashi** [comment]
I tried and ot this error,
`/C:/src/flutter/.pub-cache/git/webviewx-5f95a924df48f6691e9acd3d61d0017780b3abc6/lib/src/view/mobile.dart:157:39: Error: A value of type 'WebViewController?' can't be assigned to a variable of type 'WebViewController' because 'WebViewController?' is nullable and 'WebViewController' isn't.
 - 'WebViewController' is from 'package:webview_flutter/webview_flutter.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-2.0.8/lib/webview_flutter.dart').
      webViewXController!.connector = originalWebViewController;`
I believe something to do with null safety

**Comment by adrianflutur** [comment]
Yes, it's related to null safety. That's why I can't publish it as 0.0.5 yet 😁
Meanwhile, please add an if-not-null check inside `onWebViewCreated` and set your controller inside it.

**Comment by adrianflutur** [comment]
@CodingWithTashi Hi, you might want to try again now.
https://github.com/adrianflutur/webviewx/pull/14

**Comment by CodingWithTashi** [comment]
@adrianflutur seems working fine in real devices, but for emulator still I am getting black screen. anyway we will be using real device end of the day. it would be fine I think.

**Comment by adrianflutur** [comment]
@CodingWithTashi Thats good,
Yes, adding desktop support is on the list, but it's somewhat a long-term thing because `platform-views` are not yet implemented for theese platforms.
In fact, Linux platform-views are currently waiting to be merged here https://github.com/flutter/engine/pull/26288 , so maybe it's not going to take so long after all :)

Also closing this now, so please open a new issue if you have any other problems. Thanks!
