### ISSUE TITLE
Session data not preserved in web

### ISSUE THREAD

**Issue by Saim20** [adrianflutur/webviewx#15]
I prserved a data in the session variable, 
`$_SESSION['final_amount'] = some_value`
but when it is accessed in another page in the same webview says undefined final_amount

**Comment by adrianflutur** [comment]
Hi, please provide more details.
How do you use the package? Can you post the full code?
Thanks

**Comment by Saim20** [comment]
> Hi, please provide more details.
> How do you use the package? Can you post the full code?
> Thanks

Sure
`@override
  Widget build(BuildContext context) {
    var data =
        ModalRoute.of(context)!.settings.arguments as Map<String, dynamic>;
    Order order = data['order'];
    Function clearCart = data['clearCart'];
    totalCost = order.totalCost;

    PaymentRequest paymentRequest =
        PaymentRequest(amount: totalCost, intent: 'sale');
    String encodedRequest = paymentRequest.toString(); 

    return Container(
      child: Scaffold(
        appBar: AppBar(
          elevation: 0.0,
          backgroundColor: Colors.transparent,
        ),
        body:
            Container(
          child: WebViewX(
            javascriptMode: JavascriptMode.unrestricted,
            webSpecificParams: WebSpecificParams(
              webAllowFullscreenContent: true,
              additionalSandboxOptions:['allow-same-origin'],
            ),
            onWebViewCreated: (WebViewXController controller) {
              _controller = controller;
            },
            dartCallBacks: {
              getData(context, clearCart, order),
            },
            initialContent: '$paymentUrl?amount=${paymentRequest.amount}',
            initialSourceType: SourceType.URL,
          ),
        ),
      ),
    );
  }

  DartCallback getData(BuildContext context, Function clearCart, Order order) {
    return DartCallback(
      name: 'getResponse',
      callBack: (response) async {
        print(response);
        // regular processing
        }
  }`

in js I hardcoded the callback for mobile, tried 
`jsContent: {EmbeddedJavascriptContent(
 // for web
// for mobile
),}`

wasnt working , so I hardcoded ,,
that isnt the issue I guess . because it works on mobile device. But php session variable is not persisting on web version

**Comment by Saim20** [comment]
Heres the code 
`@override
  Widget build(BuildContext context) {
    var data =
        ModalRoute.of(context)!.settings.arguments as Map<String, dynamic>;
    Order order = data['order'];
    Function clearCart = data['clearCart'];
    totalCost = order.totalCost;
    PaymentRequest paymentRequest =
        PaymentRequest(amount: totalCost, intent: 'sale');
    String encodedRequest = paymentRequest.toString(); 
    return Container(
      child: Scaffold(
        appBar: AppBar(
          elevation: 0.0,
          backgroundColor: Colors.transparent,
        ),
        body:
            Container(
          child: WebViewX(
            javascriptMode: JavascriptMode.unrestricted,
            webSpecificParams: WebSpecificParams(
              webAllowFullscreenContent: true,
              additionalSandboxOptions:['allow-same-origin'],
            ),
            onWebViewCreated: (WebViewXController controller) {
              _controller = controller;
            },
            dartCallBacks: {
              getData(context, clearCart, order),
            },
            initialContent: '$paymentUrl?amount=${paymentRequest.amount}',
            initialSourceType: SourceType.URL,
          ),
        ),
      ),
    );
  }

  DartCallback getData(BuildContext context, Function clearCart, Order order) {
    return DartCallback(
      name: 'getResponse',
      callBack: (response) async {
        print(response);
        // regular processing
        }
  }`

I harcoded the callback in js. as couldn't get jsContent to work. But thats unlikely to be the problem. The $_SESSION variable data is not preserved through different pages on the web, but woks fine in mobile

**Comment by adrianflutur** [comment]
I understand the problem. The thing is, an iframe is not exactly a fully fledged browser, like the mobile version is. That means there are known (and unknown!) differences between the two, which unfortunately I cannot control.

Now back to the problem. 
First, the reason why you can't use `jsContent` is that it only works for HTML or URL_BYPASS, because in those two cases the package can "download" the source and inject that JS inside that source. If you use URL as the sourceType, then the package assumes the webpage is coming from another domain (other than localhost, or where the page is located) and thus it cannot inject that JS because we do not have control over websites from other domains inside an iframe. 

Related to the $_SESSION data, honestly I didn't test it with a php backend so I'm not sure how things work out there. Does this work in a simple HTML page using an ordinary iframe? I found [THIS](https://forums.asp.net/t/1025796.aspx?Loosing+Session+Variables+in+iFrames) which says it's pretty much not possible, but otherwise I'm not really sure :/

**Comment by Saim20** [comment]
I see the issue, But is there a way to open a new tab / page then retrieve data from that page into the flutter web app? Or are cookies the closest thing to what i need?

**Comment by adrianflutur** [comment]
I suppose cookies are the solution in this case.

**Comment by Saim20** [comment]
Thanks for the help😊
