### ISSUE TITLE
get URL of a new page

### ISSUE THREAD

**Issue by lipocodes** [adrianflutur/webviewx#16]
Hi,

How can I  get informed about the new URL (full path) when I'm inside a WebView (Flutter Web project) and I clicked on a button (on the webpage) and got transmitted to a new webpage?

Thanks,
Lior

**Comment by adrianflutur** [comment]
Hi, this is currently possible using the 
```
onPageStarted: (url),
onPageFinished: (url),
```
callbacks from the WebViewX widget.

Currently on Web, they only provide iframe's source (srcDoc), not the URL.
Indeed it would be a good idea to have the URL in there. I'll try to change this and notity you if its possible.

**Comment by nomanmurtaza786** [comment]
> Hi, this is currently possible using the
> 
> ```
> onPageStarted: (url),
> onPageFinished: (url),
> ```
> 
> callbacks from the WebViewX widget.
> 
> Currently on Web, they only provide iframe's source (srcDoc), not the URL.
> Indeed it would be a good idea to have the URL in there. I'll try to change this and notity you if it worked.

Any update need URL in callback

**Comment by adrianflutur** [comment]
Yes, didn't have enough time to look into it, will check out ASAP

**Comment by adrianflutur** [comment]
Done https://github.com/adrianflutur/webviewx/pull/26
You can use `onPageStarted` and `onPageFinished` to get the next url, just like on mobile.
You can get the package from github until I publish a new version on pub.dev.
Closing this.
