### ISSUE TITLE
Null safe

### ISSUE THREAD

**Issue by tmartineau** [adrianflutur/webviewx#2]
Are you considering adding in null safe? Or is there a way to run this in a project using Null safety?

**Comment by adrianflutur** [comment]
Hi, null safety isn't really a priority right now, especially considering I'm not yet used to deal with nullable types.
But yeah, it will be available at some point in the future.

Regarding running this in a null safety project, yes it's possible but if you use packages that are not null safe, then your proiect will become so-called "unsound" null safe. You can read here more about this: https://dart.dev/null-safety/unsound-null-safety.
Thanks

**Comment by tmartineau** [comment]
Thanks for the reply! I will look into that and keep an eye on the project for when it get's null safety.
