### ISSUE TITLE
Intercept navigationDelegate, onLoaded...

### ISSUE THREAD

**Issue by jasonlaw** [adrianflutur/webviewx#20]
Hi,

I would like to replace the current WebView with this to support for both mobile and web.
However, I find no way to handle the events such as navigationDelegate, onLoaded...
May I know how to do that?

Basically, I need to make sure this is work seamlessly as WebView before going further for web improvement.

Thanks!

**Comment by adrianflutur** [comment]
Hi, a working navigationDelegate is a little bit tricky to implement, I'll try to look into it ASAP.
The onLoaded callback is available as two separate `onPageStarted` and `onPageFinished` callbacks, like in the mobile version.

**Comment by adrianflutur** [comment]
Done #26
navigationDelegate only works for `SourceType.urlBypass` for now. This may change soon.
You can use onPageStarted and onPageFinished to get the next url, just like on mobile.
You can get the package from github until I publish a new version on pub.dev.
Closing this.
