### ISSUE TITLE
can't scroll

### ISSUE THREAD

**Issue by EightRice** [adrianflutur/webviewx#25]
is there an example of how to add this and allow gestures like scrolling? Setting ignoreAllGestures to false doesn't seem to do the trick. can't scroll while cursor is over the embedded content.

**Comment by adrianflutur** [comment]
Hi, ignoreAllGestures toggles all gestures on/off, it doesn't have anything to do with *allowing* scroll gestures.

On web scrolling works by default. 
On mobile, it also does work by default in some limited use-cases. If you're doing something nasty such as nesting webviews inside a `ListView`, then you need to supply a `Set<Factory<OneSequenceGestureRecognizer>>` (as instructed [HERE](https://youtu.be/RA-vLF_vnng?t=140) by the official Flutter team) to the `mobileSpecificParams`'s `mobileGestureRecognizers` parameter.
You can find an example on how to do this [HERE](https://github.com/adrianflutur/webviewx/blob/main/lib/src/utils/mobile_specific_params.dart).

**Comment by EightRice** [comment]
I'm on web, and it definitely doesn't scroll. This is what I'm doing inside of a Stateful widget:

```
 String link =
      "https://docs.google.com/presentation/d/e/2PACX-1vSO7iCXx36hcojFSn82zLZ9VCORh40wE2Pps8lhskfQVvqacFGYqNI_iI8HuJEQxeeXgdP-9dlllFgW/embed";
  @override
  Widget build(BuildContext context) {
    return WebViewX(
      initialContent: link,
      initialSourceType: SourceType.URL,
          height: MediaQuery.of(context).size.height,
          width: MediaQuery.of(context).size.width,
        );
  }
```

**Comment by EightRice** [comment]
> Hi, ignoreAllGestures toggles all gestures on/off, it doesn't have anything to do with _allowing_ scroll gestures.
> 
> On web scrolling works by default.
> On mobile, it also does work by default in some limited use-cases. If you're doing something nasty such as nesting webviews inside a `ListView`, then you need to supply a `Set<Factory<OneSequenceGestureRecognizer>>` (as instructed [HERE](https://youtu.be/RA-vLF_vnng?t=140) by the official Flutter team) to the `mobileSpecificParams`'s `mobileGestureRecognizers` parameter.
> You can find an example on how to do this [HERE](https://github.com/adrianflutur/webviewx/blob/main/lib/src/utils/mobile_specific_params.dart).

Do you also have an example of a working code for web?

**Comment by EightRice** [comment]
I modified your example and it does indeed scroll. Not sure what about makes it work, but I'm glad it does. thanks!

**Comment by EightRice** [comment]
Update: got it to work by making the height fixed and ignoring gestures

**Comment by impatelravi** [comment]
@EightRice Can you please share your code? I'm also facing the same issue.
