### ISSUE TITLE
query parapmeters in urlbypass mode 

### ISSUE THREAD

**Issue by k1Akbarpour** [adrianflutur/webviewx#28]
when is use urlbypass source type , query parameters not detect on target web app.
what is my problem?

**Comment by k1Akbarpour** [comment]
.

**Comment by k1Akbarpour** [comment]
.

**Comment by adrianflutur** [comment]
Hi, can you provide more details? There shouldn't be any issues regarding to query params.

**Comment by adrianflutur** [comment]
Closing this, please open a new issue if you still have this problem.
