### ISSUE TITLE
Height / Width parameters marked as nullable while they aren't

### ISSUE THREAD

**Issue by franarolas** [adrianflutur/webviewx#31]
If you don't set the height and the width the plugin throws null pointer exception.

**Comment by adrianflutur** [comment]
Hi, yeah it seems that I forgot to add a LayoutBuilder over the WebViewX widget. There are a few issues which I need to address first, so in the meanwhile you can just add a LayoutBuilder in your own app.

**Comment by adrianflutur** [comment]
[This has been addressed](https://github.com/adrianflutur/webviewx/blob/main/CHANGELOG.md)

Closing this, let me know if you encounter any other issues.
