### ISSUE TITLE
camera and microphone has been denied access from inside iFrame

### ISSUE THREAD

**Issue by phankhanhhung** [adrianflutur/webviewx#35]
Please help.

**Comment by adrianflutur** [comment]
Hi, I think you can solve this pretty easy.
Check this out: https://stackoverflow.com/questions/57008648/accessing-camera-and-mic-in-sandboxed-iframe-from-different-subdomain

You can add other "allow" options on the package by specifying them as:
```dart
webSpecificParams: WebSpecificParams(
  additionalAllowOptions: [
    'camera', // or 'camera https://your_website.com'
    'microphone', // or 'microphone https://your_website.com'
  ],
)
```

**Comment by adrianflutur** [comment]
Closing this for now, please open another issue if you encounter any other issues.
