### ISSUE TITLE
Issue in opening google.com while using URLBypass in flutter webviewx on flutter web

### ISSUE THREAD

**Issue by parammittal16** [adrianflutur/webviewx#4]
Hey I am using flutter web 2.0.4 stable

![image](https://user-images.githubusercontent.com/31361983/114270211-c803e580-9a28-11eb-9200-3ce0b6d9a5ff.png)

Getting this error while accessing google.com or any other web site using URLBypass

![image](https://user-images.githubusercontent.com/31361983/114270257-fb467480-9a28-11eb-9cb4-15e215afb4d7.png)
 here is my code 

My flutter doctor:
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale
    en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.0-rc1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (1 available)

**Comment by adrianflutur** [comment]
Hi, yes this is a known small issue.
Add a slash ('/') at the end of the URL to fix it.
I'm working on a (hopefully) more robust solution to pass data from Dart to JS.

**Comment by parammittal16** [comment]
Working fine now Thanks @adrianflutur

**Comment by adrianflutur** [comment]
Alright, closing this.
