### ISSUE TITLE
How to set initial zoom level?

### ISSUE THREAD

**Issue by khafabi** [adrianflutur/webviewx#43]
Hi I am kinda new to flutter and this package does help me to achieve my goal but i need to tweak it, so how can I set the zoom level for the widget when runnning on the Web? thanks

**Comment by adrianflutur** [comment]
Hi, I'm not sure what you mean by 'zoom', can you elaborate?

**Comment by khafabi** [comment]
Hi, my apologize for the lack of clarity in my question

I was trying to set up the Webviewx widget with initial zoom due to the page which I want to show is quite big.
But I have accomplished what I need using Transform widget. 
So yeah, we can close this issue
Sorry for the inconvenience.
