### ISSUE TITLE
Add null safety

### ISSUE THREAD

**Issue by lucasimpactasp** [adrianflutur/webviewx#5]

**Comment by adrianflutur** [comment]
I wish to add null safety as much as the next person, but I'm currently extremely busy and there are still many bugs to be addressed.
Meanwhile, you can fork the project anytime and add null safety yourself, maybe even submit a pull request to another branch if you wish.

**Comment by Azzeccagarbugli** [comment]
Probably https://github.com/adrianflutur/webviewx/pull/9 could help with this 👋

**Comment by adrianflutur** [comment]
@Azzeccagarbugli Hi, thanks for taking the time to migrate it. I'll review and test it ASAP (this weekend, hopefully) 😀

**Comment by adrianflutur** [comment]
Merged into main. Thanks!
