### ISSUE TITLE
Javascript Bridge Problems on the Web

### ISSUE THREAD

**Issue by Jihun9999999** [adrianflutur/webviewx#8]
// in dart

dartCallBacks: Set.from([
        DartCallback(
          name: "test",
          callBack: (message) {
            showSnackBar('${message.toString()}', context);
          },
        ),
      ]),

void _evalRawJsInGlobalContext() async {
    try {
      var result = await _wc.evalRawJavascript(
        "jstestFunction('test')",
      );
    } catch (e) {
      showAlertDialog("${e}", context);
    }
  }

// in html

<script>
      function jstestFunction(text){
        console.log(text);
        if (window.test && window.test.postMessage) {
          console.log(document.documentElement.innerHTML);
          test.postMessage(text);
          test(text);
        }
      }
    </script>

// output
mobile : 'test'
web : nosuchmethod: invalid member on null:'callmethod'

I want to show the values ​​returned by the web using dartcallback and evalRawJavascript. Obviously, it works well on mobile, but when I run it on the web, I get an error message saying nosuchmethod: invalid member on null:'callmethod'. If I misunderstand and use it strangely, please explain how to fix it. Or, if you can't support it on the web, please tell us.

This article uses Google Translator.
thank you.

**Comment by adrianflutur** [comment]
Hi, yes I see what's happening here.

The problem is that you hard-coded the `jstestFunction` function inside your html page, and inside this function you call both `test.postMessage(text)` (which is for mobile only) and `test(text)`, (which is for web only). 
When the web version calls `test.postMessage(text)`, the `test` object doesn't exist (it is null), so it throws a NoSuchMethod on null.

To solve this, you should use the `jsContent` parameter from the `WebViewX` widget, like this:
```dart
...
return WebViewX(
      key: ValueKey('webviewx'),
      initialContent: initialContent,
      initialSourceType: SourceType.HTML,
      ...
      ...
      ...
      jsContent: {
        EmbeddedJsContent(
          webJs:
              "function jstestFunction(text) { test(text) }",
          mobileJs:
              "function jstestFunction(text) { test.postMessage(text) }",
        ),
      },
```
, and it will work (tested 😉)

**Comment by Jihun9999999** [comment]
> 안녕하세요, 예, 여기서 무슨 일이 일어나고 있는지 봅니다.
> 
> 문제는 `jstestFunction`HTML 페이지 내 에서 함수 를 하드 코딩했으며이 함수 내에서 `test.postMessage(text)`(모바일 전용) 및 `test(text)`, (웹 전용)을 모두 호출한다는 것 입니다.
> 웹 버전이를 호출 `test.postMessage(text)`하면 `test`객체가 존재하지 않으므로 (null 임) null에 NoSuchMethod가 발생합니다.
> 
> 이를 해결하려면 다음 과 같이 위젯 의 `jsContent`매개 변수를 사용해야합니다 `WebViewX`.
> 
> ```dart
> ...
>  return  WebViewX (
>       키 :  ValueKey ( 'webviewx' ),
>       initialContent : initialContent,
>       initialSourceType :  SourceType . HTML ,
>       ...
>       ...
>       ...
>       jsContent : {
>          EmbeddedJsContent (
>           webJs : 
>               "function jstestFunction (text) {test (text)}" ,
>           mobileJs : 
>               "function jstestFunction (text) {test.postMessage (text)}" ,
>         ),
>       },
> ```
> 
> , 작동합니다 (테스트 😉)

if use sourtype : url,

**Comment by Jihun9999999** [comment]
> 안녕하세요, 예, 여기서 무슨 일이 일어나고 있는지 봅니다.
> 
> 문제는 `jstestFunction`HTML 페이지 내 에서 함수 를 하드 코딩했으며이 함수 내에서 `test.postMessage(text)`(모바일 전용) 및 `test(text)`, (웹 전용)을 모두 호출한다는 것 입니다.
> 웹 버전이를 호출 `test.postMessage(text)`하면 `test`객체가 존재하지 않으므로 (null 임) null에 NoSuchMethod가 발생합니다.
> 
> 이를 해결하려면 다음 과 같이 위젯 의 `jsContent`매개 변수를 사용해야합니다 `WebViewX`.
> 
> ```dart
> ...
>  return  WebViewX (
>       키 :  ValueKey ( 'webviewx' ),
>       initialContent : initialContent,
>       initialSourceType :  SourceType . HTML ,
>       ...
>       ...
>       ...
>       jsContent : {
>          EmbeddedJsContent (
>           webJs : 
>               "function jstestFunction (text) {test (text)}" ,
>           mobileJs : 
>               "function jstestFunction (text) {test.postMessage (text)}" ,
>         ),
>       },
> ```
> 
> , 작동합니다 (테스트 😉)

Should I use html type rather than url?

**Comment by Jihun9999999** [comment]
use type is url.....I've used it exactly as you said, but I still have problems. Need to change the html code?

**Comment by Jihun9999999** [comment]
class _WebXState extends State<WebX> {

  final _url = "https://jihun9999999.github.io/web/javabridge.html";

  WebViewXController _wc = WebViewXController();

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.all(5.0),
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Expanded(flex: 3, child: _webView()),
          Expanded(child: _button()),
        ],
      ),
    );
  }

  Widget _webView() {
    return WebViewX(
      key: ValueKey('webviewx'),
      initialContent: _url,
      onWebViewCreated: (controller) {
        _wc = controller;
      },
      initialSourceType: SourceType.URL,
      javascriptMode: JavascriptMode.unrestricted,
      webSpecificParams: WebSpecificParams(
        printDebugInfo: true,
        webAllowFullscreenContent: true
      ),
      mobileSpecificParams: MobileSpecificParams(
        debuggingEnabled: true,
        gestureNavigationEnabled: true,
        navigationDelegate: (navigation) {
          _launchURL(navigation.content);
          return NavigationDecision.navigate;
        },
      ),
      dartCallBacks: Set.from([
        DartCallback(
          name: "test",
          callBack: (message) {
            showSnackBar('${message.toString()}', context);
          },
        ),
      ]),
      jsContent : {
        EmbeddedJsContent (
          webJs :
          "function jstestFunction (text) { test (text) }" ,
          mobileJs :
          "function jstestFunction (text) { test.postMessage (text) }" ,
        ),
      },
    );
  }

  Widget _button() {
    return Center(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          ElevatedButton(
            onPressed: () => _evalRawJsInGlobalContext(),
            child: Text("Get JavaScript"),
          ),
          ElevatedButton(
            onPressed: () => _getWebviewContent(),
            child: Text("Get Web Contents"),
          )
        ],
      ),
    );
  }

  void _evalRawJsInGlobalContext() async {
    try {
      var result = await _wc.evalRawJavascript(
        "jstestFunction('test')",
      );
    } catch (e) {
      showAlertDialog("${e}", context);
    }
  }

  void _getWebviewContent() async {
    try {
      var content = await _wc.getContent();
      showAlertDialog(content.source, context);
    } catch (e) {
      showAlertDialog('Failed to execute this task.', context);
    }
  }
}


We will give you the full code. What should I do in this case?


2021년 5월 10일 (월) 오전 12:39, Adrian Flutur ***@***.***>님이 작성:

**Comment by adrianflutur** [comment]
Yes, you need to use `URL_BYPASS` instead of `URL`, in order to be able to interact with the web page.

**Comment by Saim20** [comment]
Flutter web callback not working, i hardcoded the callbacks in js. Works in mobile
